{
 "title": "FastAPI Metrics",
 "tags": [
  "fastapi",
  "prometheus"
 ],
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Clip Streams",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(clip_views_total)", "legendFormat": "Total Streams" }
   ]
  },
  {
   "title": "Streams by Clip ID",
   "type": "stat",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (clip_id) (clip_views_total)",
     "legendFormat": "Clip {{clip_id}}"
    }
   ]
  },
  {
   "title": "Streams by Genre",
   "type": "stat",
   "gridPos": { "x": 0, "y": 4, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (genre) (clip_views_total)",
     "legendFormat": "{{genre}}"
    }
   ]
  },
  {
   "title": "Total Clips Created",
   "type": "stat",
   "gridPos": { "x": 8, "y": 4, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "sum(clip_creates_total)", "legendFormat": "Total Created" }
   ]
  },
  {
   "title": "Clips Created by Genre",
   "type": "stat",
   "gridPos": { "x": 0, "y": 8, "w": 8, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (genre) (clip_creates_total)",
     "legendFormat": "{{genre}}"
    }
   ]
  }
 ]
}